version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: fruit-storage-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: